In [1]:
!pip install requests

Requirement already satisfied: requests in c:\users\mr laptop\anaconda3\lib\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\mr laptop\anaconda3\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mr laptop\anaconda3\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mr laptop\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mr laptop\anaconda3\lib\site-packages (from requests) (2026.6.17)

In [5]:
# Link of Books data
import requests
URL = "https://stephen-king-api.onrender.com/api/books"

# to send request we are using request method
req = requests.get(URL)
req

In [7]:
json_data = req.json()

In [21]:
json_data

In [12]:
# To convert into PandaFrame
import pandas as pd
#What is json_normalize? : It is a built-in Pandas semi-structured data normalizer.The Function: It evaluates semi-structured JSON data and 
# flattens it into a 2D table (rows and columns
df = pd.json_normalize(json_data["data"]) 
df

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]
63,72,1979,The Roopak Zone,the-roopak-zone,Viking Press,978-0-670-26069697-5,428,"[Runner-up (2nd place), Locus Award for Best F...",2026-06-26T18:20:32.285Z,[]

In [13]:
# To filter data 
df = df[['id', 'Year', 'Title', 'ISBN']]
df

    id  Year            Title                  ISBN
0    1  1974           Carrie     978-0-385-08695-0
1    2  1975      Salem's Lot     978-0-385-00751-1
2    3  1977      The Shining     978-0-385-12167-5
3    4  1977             Rage     978-0-451-07645-8
4    5  1978        The Stand     978-0-385-12168-2
..  ..   ...              ...                   ...
59  60  2018        Elevation     978-1-98210-231-9
60  61  2019    The Institute     978-1-98211-056-7
61  62  2021            Later     978-1-78909-649-1
62  63  2021    Billy Summers     978-1-982-17361-6
63  72  1979  The Roopak Zone  978-0-670-26069697-5

[64 rows x 4 columns]

In [17]:
# To fetch data of Dogs
dog_url = 'https://dogapi.dog/api/v2/breeds'
req1 = requests.get(dog_url)
req1

In [18]:
# method to check what data APIs return
print(req1.headers["Content-Type"])

application/vnd.api+json; charset=utf-8

In [22]:
json_data = req1.json()
json_data

In [20]:
# TO convert into dataframe
df1 = pd.json_normalize(json_data["data"])
df1

,id,type,attributes.name,attributes.description,attributes.life.max,attributes.life.min,attributes.male_weight.max,attributes.male_weight.min,attributes.female_weight.max,attributes.female_weight.min,attributes.hypoallergenic,relationships.group.data.id,relationships.group.data.type
0,036feed0-da8a-42c9-ab9a-57449b530b13,breed,Affenpinscher,The Affenpinscher is a small and playful breed...,16,14,5,3,5,3,True,f56dc4b1-ba1a-4454-8ce2-bd5d41404a0c,group
1,dd9362cc-52e0-462d-b856-fccdcf24b140,breed,Afghan Hound,The Afghan Hound is a large and elegant breed ...,14,12,27,23,25,20,False,be0147df-7755-4228-b132-2518c0c6d10d,group
2,1460844f-841c-4de8-b788-271aa4d63224,breed,Airedale Terrier,The Airedale Terrier is a large and powerful b...,14,12,23,20,20,18,False,1bbf373b-1937-4e73-9863-45385daa4979,group
3,e7e99424-d514-4b56-9f0c-05736f6dd22d,breed,Akita,"The Akita is a large, muscular dog breed that ...",12,10,60,35,50,35,False,56081cf0-fdf2-4114-9bf7-23a3f5b6af91,group
4,667c7359-a739-4f2b-abb4-98867671e375,breed,Alaskan Klee Kai,The Alaskan Klee Kai is a small to medium-size...,15,12,7,6,7,6,False,8000793f-a1ae-4ec4-8d55-ef83f1f644e5,group
...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,095a1856-6506-478d-a7a8-206847d5e702,breed,Wirehaired Vizsla,The Wirehaired Vizsla is a medium-sized breed ...,15,12,30,25,30,25,False,ab110192-e41b-43ff-a630-f7aee156b33a,group
279,c6b12b96-9f53-445b-8f3e-bf867c761dca,breed,Working Kelpie,The Working Kelpie is a medium-sized breed of ...,15,12,20,16,20,16,False,8000793f-a1ae-4ec4-8d55-ef83f1f644e5,group
280,43cdadb4-851b-4a3a-99c1-5f63d08d97f8,breed,Xoloitzcuintli,"The Xoloitzcuintli, also known as the Mexican ...",15,12,15,10,15,10,True,7f6ea988-366a-4e20-b4ba-4d04274fea61,group
281,052684bc-a484-4f29-b953-d5ccf6a3d5e6,breed,Yakutian Laika,The Yakutian Laika is a medium-sized breed of ...,15,12,30,18,30,18,False,8000793f-a1ae-4ec4-8d55-ef83f1f644e5,group
282,ce40589c-295a-4259-9e83-711854db8129,breed,Yorkshire Terrier,"The Yorkshire Terrier is a small, intelligent ...",15,12,3,2,3,2,False,f56dc4b1-ba1a-4454-8ce2-bd5d41404a0c,group